image:
  file: .gitpod.Dockerfile
tasks:
  - name: Database
    init: >
      sudo apt-get install postgresql
    command: >
      sudo service postgresql start

  - name: Redis
    init: >
      sudo apt-get install redis
    command: sudo service redis-server start
  
  - name: global packages
    init: >
      yarn
      yarn global add next heroku 
      gp sync-done global

  - name: format
    init: >
      gp sync-await global
    command: yarn run prisma:watch

  - name: dev
    init: >
      gp sync-await global
    command: yarn run dev:watch
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: true