image:
  file: .gitpod.Dockerfile
tasks:
  - name: Database
    init: >
      sudo apt-get install postgresql
    command: >
      sudo service postgresql start
    openMode: split-left

  - name: Redis
    init: >
      sudo apt-get install redis
    command: sudo service redis-server start
    openMode: tab-before

  - name: format
    init: >
      yarn
    command: yarn run prisma:watch
    openMode: split-right

  - name: dev
    init: >
      yarn
    command: yarn run dev:watch
    openMode: tab-after
