image:
  file: .gitpod.Dockerfile
tasks:
  - name: Database
    init: >
      sudo apt-get install postgresql
    command: sudo service postgresql start

  - name: Redis
    init: sudo apt-get install redis
    command: sudo service redis-server start
  
  - name: Install packages
    init: >
      yarn &&
      gp sync-done install

  - name: Format
    init: gp sync-await install
    command: yarn run prisma:watch

  - name: dev
    init: gp sync-await install
    command: yarn run dev:watch
    
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: true